package model.beans;
// Generated 10/09/2020 16:10:26 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Cidades generated by hbm2java
 */
public class Cidades  implements java.io.Serializable {


     private Long id;
     private String nome;
     private Date createdAt;
     private Date updatedAt;
     private Set enderecoses = new HashSet(0);

    public Cidades() {
    }

	
    public Cidades(String nome) {
        this.nome = nome;
    }
    public Cidades(String nome, Date createdAt, Date updatedAt, Set enderecoses) {
       this.nome = nome;
       this.createdAt = createdAt;
       this.updatedAt = updatedAt;
       this.enderecoses = enderecoses;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    public Date getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
    public Set getEnderecoses() {
        return this.enderecoses;
    }
    
    public void setEnderecoses(Set enderecoses) {
        this.enderecoses = enderecoses;
    }




}


