package model.beans;
// Generated 23/11/2020 16:41:25 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Clientes generated by hbm2java
 */
public class Clientes  implements java.io.Serializable {


     private Long id;
     private Medidores medidores;
     private String nomeEmpresa;
     private String cpfCnpj;
     private int diaVencimento;
     private Date createdAt;
     private Date updatedAt;
     private Set leiturases = new HashSet(0);

    public Clientes() {
        
    }
    
    public Clientes(Medidores medidores, String nomeEmpresa, String cpfCnpj, int diaVencimento) {
        this.medidores = medidores;
        this.nomeEmpresa = nomeEmpresa;
        this.cpfCnpj = cpfCnpj;
        this.diaVencimento = diaVencimento;
    }
    public Clientes(Medidores medidores, String nomeEmpresa, String cpfCnpj, int diaVencimento, Date createdAt, Date updatedAt, Set leiturases) {
       this.medidores = medidores;
       this.nomeEmpresa = nomeEmpresa;
       this.cpfCnpj = cpfCnpj;
       this.diaVencimento = diaVencimento;
       this.createdAt = createdAt;
       this.updatedAt = updatedAt;
       this.leiturases = leiturases;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public Medidores getMedidores() {
        return this.medidores;
    }
    
    public void setMedidores(Medidores medidores) {
        this.medidores = medidores;
    }
    public String getNomeEmpresa() {
        return this.nomeEmpresa;
    }
    
    public void setNomeEmpresa(String nomeEmpresa) {
        this.nomeEmpresa = nomeEmpresa;
    }
    public String getCpfCnpj() {
        return this.cpfCnpj;
    }
    
    public void setCpfCnpj(String cpfCnpj) {
        this.cpfCnpj = cpfCnpj;
    }
    public int getDiaVencimento() {
        return this.diaVencimento;
    }
    
    public void setDiaVencimento(int diaVencimento) {
        this.diaVencimento = diaVencimento;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    public Date getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
    public Set getLeiturases() {
        return this.leiturases;
    }
    
    public void setLeiturases(Set leiturases) {
        this.leiturases = leiturases;
    }




}


