package model.beans;
// Generated 23/11/2020 16:41:25 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Enderecos generated by hbm2java
 */
public class Enderecos  implements java.io.Serializable {


     private Long id;
     private Cidades cidades;
     private Medidores medidores;
     private String cep;
     private String logradouro;
     private String numero;
     private String complemento;
     private String bairro;
     private String uf;
     private Date createdAt;
     private Date updatedAt;

    public Enderecos() {
    }

	
    public Enderecos(Cidades cidades, Medidores medidores, String cep, String logradouro, String numero, String complemento, String bairro, String uf) {
        this.cidades = cidades;
        this.medidores = medidores;
        this.cep = cep;
        this.logradouro = logradouro;
        this.numero = numero;
        this.complemento = complemento;
        this.bairro = bairro;
        this.uf = uf;
    }
    public Enderecos(Cidades cidades, Medidores medidores, String cep, String logradouro, String numero, String complemento, String bairro, String uf, Date createdAt, Date updatedAt) {
       this.cidades = cidades;
       this.medidores = medidores;
       this.cep = cep;
       this.logradouro = logradouro;
       this.numero = numero;
       this.complemento = complemento;
       this.bairro = bairro;
       this.uf = uf;
       this.createdAt = createdAt;
       this.updatedAt = updatedAt;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public Cidades getCidades() {
        return this.cidades;
    }
    
    public void setCidades(Cidades cidades) {
        this.cidades = cidades;
    }
    public Medidores getMedidores() {
        return this.medidores;
    }
    
    public void setMedidores(Medidores medidores) {
        this.medidores = medidores;
    }
    public String getCep() {
        return this.cep;
    }
    
    public void setCep(String cep) {
        this.cep = cep;
    }
    public String getLogradouro() {
        return this.logradouro;
    }
    
    public void setLogradouro(String logradouro) {
        this.logradouro = logradouro;
    }
    public String getNumero() {
        return this.numero;
    }
    
    public void setNumero(String numero) {
        this.numero = numero;
    }
    public String getComplemento() {
        return this.complemento;
    }
    
    public void setComplemento(String complemento) {
        this.complemento = complemento;
    }
    public String getBairro() {
        return this.bairro;
    }
    
    public void setBairro(String bairro) {
        this.bairro = bairro;
    }
    public String getUf() {
        return this.uf;
    }
    
    public void setUf(String uf) {
        this.uf = uf;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    public Date getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }




}


