package model.beans;
// Generated 23/11/2020 16:41:25 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Medidores generated by hbm2java
 */
public class Medidores  implements java.io.Serializable {


     private Long id;
     private String numero;
     private String grupo;
     private String classe;
     private String ligacao;
     private String faturamento;
     private String modalidade;
     private String status;
     private Date createdAt;
     private Date updatedAt;
     private Set clienteses = new HashSet(0);
     private Set leiturases = new HashSet(0);
     private Set enderecoses = new HashSet(0);

    public Medidores() {
    }

	
    public Medidores(String numero, String grupo, String classe, String ligacao, String faturamento, String modalidade, String status) {
        this.numero = numero;
        this.grupo = grupo;
        this.classe = classe;
        this.ligacao = ligacao;
        this.faturamento = faturamento;
        this.modalidade = modalidade;
        this.status = status;
    }
    public Medidores(String numero, String grupo, String classe, String ligacao, String faturamento, String modalidade, String status, Date createdAt, Date updatedAt, Set clienteses, Set leiturases, Set enderecoses) {
       this.numero = numero;
       this.grupo = grupo;
       this.classe = classe;
       this.ligacao = ligacao;
       this.faturamento = faturamento;
       this.modalidade = modalidade;
       this.status = status;
       this.createdAt = createdAt;
       this.updatedAt = updatedAt;
       this.clienteses = clienteses;
       this.leiturases = leiturases;
       this.enderecoses = enderecoses;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public String getNumero() {
        return this.numero;
    }
    
    public void setNumero(String numero) {
        this.numero = numero;
    }
    public String getGrupo() {
        return this.grupo;
    }
    
    public void setGrupo(String grupo) {
        this.grupo = grupo;
    }
    public String getClasse() {
        return this.classe;
    }
    
    public void setClasse(String classe) {
        this.classe = classe;
    }
    public String getLigacao() {
        return this.ligacao;
    }
    
    public void setLigacao(String ligacao) {
        this.ligacao = ligacao;
    }
    public String getFaturamento() {
        return this.faturamento;
    }
    
    public void setFaturamento(String faturamento) {
        this.faturamento = faturamento;
    }
    public String getModalidade() {
        return this.modalidade;
    }
    
    public void setModalidade(String modalidade) {
        this.modalidade = modalidade;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    public Date getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
    public Set getClienteses() {
        return this.clienteses;
    }
    
    public void setClienteses(Set clienteses) {
        this.clienteses = clienteses;
    }
    public Set getLeiturases() {
        return this.leiturases;
    }
    
    public void setLeiturases(Set leiturases) {
        this.leiturases = leiturases;
    }
    public Set getEnderecoses() {
        return this.enderecoses;
    }
    
    public void setEnderecoses(Set enderecoses) {
        this.enderecoses = enderecoses;
    }




}


