package model.beans;
// Generated 23/11/2020 16:41:25 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Recursos generated by hbm2java
 */
public class Recursos  implements java.io.Serializable {


     private Long id;
     private String descricao;
     private Date createdAt;
     private Date updatedAt;
     private Set permissoeses = new HashSet(0);

    public Recursos() {
    }

	
    public Recursos(String descricao) {
        this.descricao = descricao;
    }
    public Recursos(String descricao, Date createdAt, Date updatedAt, Set permissoeses) {
       this.descricao = descricao;
       this.createdAt = createdAt;
       this.updatedAt = updatedAt;
       this.permissoeses = permissoeses;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    public Date getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
    public Set getPermissoeses() {
        return this.permissoeses;
    }
    
    public void setPermissoeses(Set permissoeses) {
        this.permissoeses = permissoeses;
    }




}


