package model.beans;
// Generated 23/11/2020 16:41:25 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
public class Users implements java.io.Serializable {

    private Long id;
    private Grupos grupos;
    private String name;
    private String email;
    private Date emailVerifiedAt;
    private String password;
    private String rememberToken;
    private Date createdAt;
    private Date updatedAt;
    private Set permissoeses = new HashSet(0);

    public Users() {
    }

    public Users(String name, String email, String password) {
        this.grupos = grupos;
        this.name = name;
        this.email = email;
        this.password = password;
    }

    public Users(Grupos grupos, String name, String email, String password) {
        this.grupos = grupos;
        this.name = name;
        this.email = email;
        this.password = password;
    }

    public Users(Grupos grupos, String name, String email, Date emailVerifiedAt, String password, String rememberToken, Date createdAt, Date updatedAt, Set permissoeses) {
        this.grupos = grupos;
        this.name = name;
        this.email = email;
        this.emailVerifiedAt = emailVerifiedAt;
        this.password = password;
        this.rememberToken = rememberToken;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
        this.permissoeses = permissoeses;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Grupos getGrupos() {
        return this.grupos;
    }

    public void setGrupos(Grupos grupos) {
        this.grupos = grupos;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public Date getEmailVerifiedAt() {
        return this.emailVerifiedAt;
    }

    public void setEmailVerifiedAt(Date emailVerifiedAt) {
        this.emailVerifiedAt = emailVerifiedAt;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getRememberToken() {
        return this.rememberToken;
    }

    public void setRememberToken(String rememberToken) {
        this.rememberToken = rememberToken;
    }

    public Date getCreatedAt() {
        return this.createdAt;
    }

    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    public Date getUpdatedAt() {
        return this.updatedAt;
    }

    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    public Set getPermissoeses() {
        return this.permissoeses;
    }

    public void setPermissoeses(Set permissoeses) {
        this.permissoeses = permissoeses;
    }

}
