package model.beans;
// Generated 10/09/2020 16:10:26 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;

/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private Long id;
     private String name;
     private String email;
     private Date emailVerifiedAt;
     private String password;
     private String rememberToken;     
     private Date createdAt;     
     private Date updatedAt;

    public Users() {
    }

	
    public Users(String name, String email, String password) {
        this.name = name;
        this.email = email;
        this.password = password;
    }
    public Users(String name, String email, Date emailVerifiedAt, String password, String rememberToken, Date createdAt, Date updatedAt) {
       this.name = name;
       this.email = email;
       this.emailVerifiedAt = emailVerifiedAt;
       this.password = password;
       this.rememberToken = rememberToken;
       this.createdAt = createdAt;
       this.updatedAt = updatedAt;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Date getEmailVerifiedAt() {
        return this.emailVerifiedAt;
    }
    
    public void setEmailVerifiedAt(Date emailVerifiedAt) {
        this.emailVerifiedAt = emailVerifiedAt;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getRememberToken() {
        return this.rememberToken;
    }
    
    public void setRememberToken(String rememberToken) {
        this.rememberToken = rememberToken;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    public Date getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }




}


